<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $connection = env('BILLING_DB_CONNECTION', 'billing_mysql');
        DB::connection($connection)->table('products')->insert([
            [
                'name' => 'Smart LED TV 215',
                'sku' => 'SKU5035',
                'category_id' => 5,
                'purchase_price' => 2979.66,
                'selling_price' => 3698.88,
                'stock' => 32,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Bluetooth Speaker 286',
                'sku' => 'SKU4818',
                'category_id' => 2,
                'purchase_price' => 4216.39,
                'selling_price' => 4901.18,
                'stock' => 72,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Smart LED TV 199',
                'sku' => 'SKU6757',
                'category_id' => 1,
                'purchase_price' => 1168.78,
                'selling_price' => 1342.39,
                'stock' => 96,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Blender 40',
                'sku' => 'SKU2105',
                'category_id' => 1,
                'purchase_price' => 4631.93,
                'selling_price' => 5832.28,
                'stock' => 99,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Cookware Set 295',
                'sku' => 'SKU6685',
                'category_id' => 5,
                'purchase_price' => 611.43,
                'selling_price' => 689.28,
                'stock' => 62,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Tablet 398',
                'sku' => 'SKU5291',
                'category_id' => 5,
                'purchase_price' => 4965.88,
                'selling_price' => 6107.9,
                'stock' => 50,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Sunglasses 113',
                'sku' => 'SKU6743',
                'category_id' => 5,
                'purchase_price' => 478.75,
                'selling_price' => 593.7,
                'stock' => 43,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Fitness Tracker 249',
                'sku' => 'SKU3718',
                'category_id' => 3,
                'purchase_price' => 758.8,
                'selling_price' => 869.67,
                'stock' => 196,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Curtains 191',
                'sku' => 'SKU6409',
                'category_id' => 2,
                'purchase_price' => 2189.79,
                'selling_price' => 2538.42,
                'stock' => 148,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Fiction Novel 191',
                'sku' => 'SKU6922',
                'category_id' => 1,
                'purchase_price' => 3324.68,
                'selling_price' => 4265.99,
                'stock' => 36,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Fitness Tracker 255',
                'sku' => 'SKU6626',
                'category_id' => 5,
                'purchase_price' => 3672.9,
                'selling_price' => 4110.43,
                'stock' => 196,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Sneakers 238',
                'sku' => 'SKU6144',
                'category_id' => 4,
                'purchase_price' => 230.41,
                'selling_price' => 283.42,
                'stock' => 24,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Sneakers 335',
                'sku' => 'SKU5543',
                'category_id' => 1,
                'purchase_price' => 1246.26,
                'selling_price' => 1552.94,
                'stock' => 36,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Air Conditioner 281',
                'sku' => 'SKU6453',
                'category_id' => 3,
                'purchase_price' => 1895.14,
                'selling_price' => 2445.18,
                'stock' => 91,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Desk Lamp 345',
                'sku' => 'SKU3853',
                'category_id' => 3,
                'purchase_price' => 2351.71,
                'selling_price' => 2648.3,
                'stock' => 48,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Running Shoes 370',
                'sku' => 'SKU4611',
                'category_id' => 1,
                'purchase_price' => 3440.15,
                'selling_price' => 4137.07,
                'stock' => 91,
                'unit' => 'ltr',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Smart LED TV 430',
                'sku' => 'SKU6669',
                'category_id' => 2,
                'purchase_price' => 3298.63,
                'selling_price' => 3804.58,
                'stock' => 114,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Fitness Tracker 309',
                'sku' => 'SKU7444',
                'category_id' => 2,
                'purchase_price' => 562.06,
                'selling_price' => 618.48,
                'stock' => 148,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'T-shirt 90',
                'sku' => 'SKU9144',
                'category_id' => 5,
                'purchase_price' => 769.29,
                'selling_price' => 989.77,
                'stock' => 86,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Running Shoes 169',
                'sku' => 'SKU6209',
                'category_id' => 2,
                'purchase_price' => 2959.52,
                'selling_price' => 3681.49,
                'stock' => 65,
                'unit' => 'pcs',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Sneakers 12',
                'sku' => 'SKU2859',
                'category_id' => 3,
                'purchase_price' => 752.26,
                'selling_price' => 866.58,
                'stock' => 38,
                'unit' => 'ltr',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Notebook 342',
                'sku' => 'SKU7109',
                'category_id' => 5,
                'purchase_price' => 4099.85,
                'selling_price' => 5024.68,
                'stock' => 138,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Notebook 260',
                'sku' => 'SKU7974',
                'category_id' => 1,
                'purchase_price' => 2341.21,
                'selling_price' => 2606.25,
                'stock' => 29,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Blender 272',
                'sku' => 'SKU5512',
                'category_id' => 2,
                'purchase_price' => 2789.54,
                'selling_price' => 3134.67,
                'stock' => 57,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Backkg 111',
                'sku' => 'SKU8107',
                'category_id' => 3,
                'purchase_price' => 1322.95,
                'selling_price' => 1691.21,
                'stock' => 97,
                'unit' => 'ltr',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Smart LED TV 129',
                'sku' => 'SKU3703',
                'category_id' => 4,
                'purchase_price' => 298.19,
                'selling_price' => 347.42,
                'stock' => 36,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Desk Lamp 109',
                'sku' => 'SKU2016',
                'category_id' => 1,
                'purchase_price' => 2190.15,
                'selling_price' => 2739.1,
                'stock' => 126,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Fiction Novel 70',
                'sku' => 'SKU8023',
                'category_id' => 5,
                'purchase_price' => 4308.59,
                'selling_price' => 4878.83,
                'stock' => 177,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Running Shoes 279',
                'sku' => 'SKU1291',
                'category_id' => 1,
                'purchase_price' => 3850.48,
                'selling_price' => 4972.83,
                'stock' => 153,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Bluetooth Speaker 6',
                'sku' => 'SKU3470',
                'category_id' => 3,
                'purchase_price' => 866.44,
                'selling_price' => 978.97,
                'stock' => 49,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Gaming Mouse 216',
                'sku' => 'SKU5445',
                'category_id' => 3,
                'purchase_price' => 3184.68,
                'selling_price' => 3612.98,
                'stock' => 141,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Backkg 423',
                'sku' => 'SKU3628',
                'category_id' => 4,
                'purchase_price' => 808.97,
                'selling_price' => 1004.05,
                'stock' => 133,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Monitor 454',
                'sku' => 'SKU9797',
                'category_id' => 1,
                'purchase_price' => 4065.57,
                'selling_price' => 5094.74,
                'stock' => 153,
                'unit' => 'ltr',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Monitor 365',
                'sku' => 'SKU9621',
                'category_id' => 3,
                'purchase_price' => 4615.63,
                'selling_price' => 5144.93,
                'stock' => 35,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Air Conditioner 351',
                'sku' => 'SKU1418',
                'category_id' => 3,
                'purchase_price' => 2280.18,
                'selling_price' => 2587.17,
                'stock' => 123,
                'unit' => 'ltr',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Yoga Mat 76',
                'sku' => 'SKU3638',
                'category_id' => 3,
                'purchase_price' => 2650.07,
                'selling_price' => 3416.04,
                'stock' => 92,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Monitor 313',
                'sku' => 'SKU7814',
                'category_id' => 4,
                'purchase_price' => 2296.64,
                'selling_price' => 2937.82,
                'stock' => 58,
                'unit' => 'ltr',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Monitor 487',
                'sku' => 'SKU4493',
                'category_id' => 3,
                'purchase_price' => 1243.09,
                'selling_price' => 1521.58,
                'stock' => 99,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Running Shoes 214',
                'sku' => 'SKU4975',
                'category_id' => 3,
                'purchase_price' => 957.62,
                'selling_price' => 1116.83,
                'stock' => 72,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Laptop Stand 236',
                'sku' => 'SKU4094',
                'category_id' => 5,
                'purchase_price' => 2714.51,
                'selling_price' => 3123.62,
                'stock' => 134,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Desk Lamp 95',
                'sku' => 'SKU7616',
                'category_id' => 4,
                'purchase_price' => 339.16,
                'selling_price' => 438.15,
                'stock' => 151,
                'unit' => 'ltr',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Vacuum Cleaner 389',
                'sku' => 'SKU2316',
                'category_id' => 2,
                'purchase_price' => 4358.17,
                'selling_price' => 5000.99,
                'stock' => 167,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Gaming Mouse 499',
                'sku' => 'SKU4932',
                'category_id' => 3,
                'purchase_price' => 3369.9,
                'selling_price' => 4299.64,
                'stock' => 100,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Sunglasses 482',
                'sku' => 'SKU9821',
                'category_id' => 5,
                'purchase_price' => 1333.35,
                'selling_price' => 1490.06,
                'stock' => 162,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Electric Toothbrush 365',
                'sku' => 'SKU7272',
                'category_id' => 3,
                'purchase_price' => 3543.18,
                'selling_price' => 3902.52,
                'stock' => 48,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Vacuum Cleaner 311',
                'sku' => 'SKU1910',
                'category_id' => 3,
                'purchase_price' => 2376.83,
                'selling_price' => 2811.76,
                'stock' => 31,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Fiction Novel 180',
                'sku' => 'SKU4143',
                'category_id' => 5,
                'purchase_price' => 2822.19,
                'selling_price' => 3251.7,
                'stock' => 50,
                'unit' => 'ltr',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Blender 229',
                'sku' => 'SKU4872',
                'category_id' => 4,
                'purchase_price' => 1787.97,
                'selling_price' => 2317.78,
                'stock' => 124,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Blender 268',
                'sku' => 'SKU2246',
                'category_id' => 1,
                'purchase_price' => 2979.48,
                'selling_price' => 3435.7,
                'stock' => 40,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Desk Lamp 25',
                'sku' => 'SKU8666',
                'category_id' => 4,
                'purchase_price' => 4972.93,
                'selling_price' => 6203.99,
                'stock' => 147,
                'unit' => 'ltr',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Fitness Tracker 299',
                'sku' => 'SKU3237',
                'category_id' => 4,
                'purchase_price' => 4843.52,
                'selling_price' => 5389.91,
                'stock' => 43,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Blender 279',
                'sku' => 'SKU1094',
                'category_id' => 1,
                'purchase_price' => 4420.1,
                'selling_price' => 5177.49,
                'stock' => 134,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Bluetooth Speaker 318',
                'sku' => 'SKU8966',
                'category_id' => 4,
                'purchase_price' => 3386.01,
                'selling_price' => 4029.33,
                'stock' => 40,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Vacuum Cleaner 261',
                'sku' => 'SKU4689',
                'category_id' => 3,
                'purchase_price' => 4890.0,
                'selling_price' => 6291.63,
                'stock' => 41,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Sneakers 8',
                'sku' => 'SKU5771',
                'category_id' => 4,
                'purchase_price' => 4531.55,
                'selling_price' => 5223.96,
                'stock' => 190,
                'unit' => 'ltr',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Fitness Tracker 42',
                'sku' => 'SKU3340',
                'category_id' => 2,
                'purchase_price' => 631.46,
                'selling_price' => 812.53,
                'stock' => 54,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Tablet 315',
                'sku' => 'SKU5020',
                'category_id' => 1,
                'purchase_price' => 2127.8,
                'selling_price' => 2472.47,
                'stock' => 47,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Laptop Stand 340',
                'sku' => 'SKU6406',
                'category_id' => 5,
                'purchase_price' => 4320.32,
                'selling_price' => 5040.78,
                'stock' => 126,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Running Shoes 223',
                'sku' => 'SKU5463',
                'category_id' => 3,
                'purchase_price' => 1971.2,
                'selling_price' => 2242.32,
                'stock' => 61,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Backkg 281',
                'sku' => 'SKU2415',
                'category_id' => 4,
                'purchase_price' => 331.29,
                'selling_price' => 401.14,
                'stock' => 160,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Fiction Novel 134',
                'sku' => 'SKU4126',
                'category_id' => 3,
                'purchase_price' => 2963.36,
                'selling_price' => 3520.8,
                'stock' => 141,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Sneakers 16',
                'sku' => 'SKU5657',
                'category_id' => 1,
                'purchase_price' => 4737.28,
                'selling_price' => 5228.06,
                'stock' => 136,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Vacuum Cleaner 489',
                'sku' => 'SKU1382',
                'category_id' => 4,
                'purchase_price' => 4369.42,
                'selling_price' => 5383.08,
                'stock' => 64,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Running Shoes 400',
                'sku' => 'SKU2847',
                'category_id' => 3,
                'purchase_price' => 4424.23,
                'selling_price' => 5059.21,
                'stock' => 34,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Blender 165',
                'sku' => 'SKU6449',
                'category_id' => 4,
                'purchase_price' => 2495.9,
                'selling_price' => 3178.1,
                'stock' => 179,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Curtains 461',
                'sku' => 'SKU4622',
                'category_id' => 2,
                'purchase_price' => 4432.98,
                'selling_price' => 5034.62,
                'stock' => 150,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Wireless Headphones 400',
                'sku' => 'SKU2319',
                'category_id' => 5,
                'purchase_price' => 3001.98,
                'selling_price' => 3886.9,
                'stock' => 193,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Air Conditioner 412',
                'sku' => 'SKU3834',
                'category_id' => 4,
                'purchase_price' => 230.95,
                'selling_price' => 280.26,
                'stock' => 63,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Monitor 286',
                'sku' => 'SKU3545',
                'category_id' => 3,
                'purchase_price' => 3082.86,
                'selling_price' => 3986.75,
                'stock' => 67,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Sunglasses 214',
                'sku' => 'SKU6826',
                'category_id' => 2,
                'purchase_price' => 4808.52,
                'selling_price' => 6048.31,
                'stock' => 198,
                'unit' => 'pcs',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Smart LED TV 9',
                'sku' => 'SKU9671',
                'category_id' => 2,
                'purchase_price' => 804.53,
                'selling_price' => 1017.38,
                'stock' => 65,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Sunglasses 189',
                'sku' => 'SKU6112',
                'category_id' => 3,
                'purchase_price' => 4678.76,
                'selling_price' => 5949.18,
                'stock' => 124,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Cookware Set 400',
                'sku' => 'SKU9152',
                'category_id' => 4,
                'purchase_price' => 534.91,
                'selling_price' => 660.05,
                'stock' => 83,
                'unit' => 'pcs',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Men Jeans 88',
                'sku' => 'SKU5160',
                'category_id' => 4,
                'purchase_price' => 4963.77,
                'selling_price' => 5637.05,
                'stock' => 131,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Fiction Novel 461',
                'sku' => 'SKU2625',
                'category_id' => 3,
                'purchase_price' => 1930.01,
                'selling_price' => 2352.86,
                'stock' => 194,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Smart LED TV 392',
                'sku' => 'SKU9566',
                'category_id' => 3,
                'purchase_price' => 935.53,
                'selling_price' => 1042.24,
                'stock' => 69,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Notebook 254',
                'sku' => 'SKU9940',
                'category_id' => 5,
                'purchase_price' => 3841.66,
                'selling_price' => 4677.31,
                'stock' => 91,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Vacuum Cleaner 125',
                'sku' => 'SKU5089',
                'category_id' => 3,
                'purchase_price' => 2394.6,
                'selling_price' => 2901.16,
                'stock' => 181,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Fitness Tracker 500',
                'sku' => 'SKU8629',
                'category_id' => 3,
                'purchase_price' => 1539.6,
                'selling_price' => 1727.99,
                'stock' => 89,
                'unit' => 'ltr',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Wireless Headphones 369',
                'sku' => 'SKU6206',
                'category_id' => 5,
                'purchase_price' => 2384.92,
                'selling_price' => 2983.04,
                'stock' => 114,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Tablet 241',
                'sku' => 'SKU1522',
                'category_id' => 2,
                'purchase_price' => 1087.0,
                'selling_price' => 1366.18,
                'stock' => 38,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Blender 291',
                'sku' => 'SKU9243',
                'category_id' => 5,
                'purchase_price' => 4480.17,
                'selling_price' => 5063.54,
                'stock' => 20,
                'unit' => 'ltr',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Men Jeans 60',
                'sku' => 'SKU1627',
                'category_id' => 1,
                'purchase_price' => 322.84,
                'selling_price' => 361.24,
                'stock' => 113,
                'unit' => 'ltr',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Curtains 322',
                'sku' => 'SKU7664',
                'category_id' => 3,
                'purchase_price' => 1865.69,
                'selling_price' => 2117.14,
                'stock' => 198,
                'unit' => 'ltr',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Yoga Mat 457',
                'sku' => 'SKU6715',
                'category_id' => 4,
                'purchase_price' => 1689.07,
                'selling_price' => 1960.63,
                'stock' => 84,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Microwave Oven 6',
                'sku' => 'SKU8988',
                'category_id' => 2,
                'purchase_price' => 647.67,
                'selling_price' => 756.29,
                'stock' => 39,
                'unit' => 'ltr',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Running Shoes 148',
                'sku' => 'SKU6233',
                'category_id' => 5,
                'purchase_price' => 2401.72,
                'selling_price' => 2932.25,
                'stock' => 164,
                'unit' => 'ltr',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Vacuum Cleaner 209',
                'sku' => 'SKU2048',
                'category_id' => 3,
                'purchase_price' => 1285.32,
                'selling_price' => 1563.89,
                'stock' => 143,
                'unit' => 'ltr',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Tablet 85',
                'sku' => 'SKU6184',
                'category_id' => 4,
                'purchase_price' => 4942.81,
                'selling_price' => 5462.26,
                'stock' => 135,
                'unit' => 'kg',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Backkg 314',
                'sku' => 'SKU3873',
                'category_id' => 5,
                'purchase_price' => 1123.82,
                'selling_price' => 1352.12,
                'stock' => 35,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Notebook 92',
                'sku' => 'SKU3816',
                'category_id' => 2,
                'purchase_price' => 2885.21,
                'selling_price' => 3401.34,
                'stock' => 30,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Cookware Set 43',
                'sku' => 'SKU3540',
                'category_id' => 2,
                'purchase_price' => 243.62,
                'selling_price' => 296.43,
                'stock' => 97,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Men Jeans 258',
                'sku' => 'SKU8528',
                'category_id' => 2,
                'purchase_price' => 2874.18,
                'selling_price' => 3272.92,
                'stock' => 188,
                'unit' => 'pcs',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Monitor 470',
                'sku' => 'SKU6399',
                'category_id' => 1,
                'purchase_price' => 4309.81,
                'selling_price' => 5361.85,
                'stock' => 118,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Gaming Mouse 411',
                'sku' => 'SKU4843',
                'category_id' => 5,
                'purchase_price' => 2309.87,
                'selling_price' => 2574.96,
                'stock' => 107,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Wireless Headphones 296',
                'sku' => 'SKU4305',
                'category_id' => 4,
                'purchase_price' => 541.04,
                'selling_price' => 690.06,
                'stock' => 142,
                'unit' => 'ltr',
                'status' => 1,
                'user_id' => 1,
            ],
            [
                'name' => 'Fitness Tracker 457',
                'sku' => 'SKU9532',
                'category_id' => 1,
                'purchase_price' => 4335.91,
                'selling_price' => 5093.9,
                'stock' => 75,
                'unit' => 'kg',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Fitness Tracker 70',
                'sku' => 'SKU5214',
                'category_id' => 1,
                'purchase_price' => 2731.58,
                'selling_price' => 3300.01,
                'stock' => 99,
                'unit' => 'ltr',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Tablet 466',
                'sku' => 'SKU5831',
                'category_id' => 1,
                'purchase_price' => 1144.17,
                'selling_price' => 1266.25,
                'stock' => 154,
                'unit' => 'ltr',
                'status' => 0,
                'user_id' => 1,
            ],
            [
                'name' => 'Desk Lamp 272',
                'sku' => 'SKU1346',
                'category_id' => 3,
                'purchase_price' => 3983.82,
                'selling_price' => 4825.98,
                'stock' => 185,
                'unit' => 'pcs',
                'status' => 1,
                'user_id' => 1,
            ],
            // Add more products here
        ]);
    }
}
